<a href="https://colab.research.google.com/github/jahed2/machine-learning-/blob/main/senti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#sentiment analysis in Adspl

In [7]:
import numpy as np
import pandas as pd
X_train = ["hey","hello","hi","good morning","good evening","hey there","yes",
"right","ok","okay","sure","fine","its_ok","it is okay","of cause","of course",
"no","dont","do not","please no","no please","never","dont do"]

y_train = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0] #1-positive 0-nagative

In [8]:
X_train

['hey',
 'hello',
 'hi',
 'good morning',
 'good evening',
 'hey there',
 'yes',
 'right',
 'ok',
 'okay',
 'sure',
 'fine',
 'its_ok',
 'it is okay',
 'of cause',
 'of course',
 'no',
 'dont',
 'do not',
 'please no',
 'no please',
 'never',
 'dont do']

#now try to data cleaning section

In [9]:
from nltk.tokenize import RegexpTokenizer

In [10]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
tokenizer = RegexpTokenizer(r'\w+')
en_stopwords = set(stopwords.words('english'))
ps = PorterStemmer()


In [13]:
def getCleanedText(text):
  text = text.lower()
  #tokenize
  tokens = tokenizer.tokenize(text)
  new_tokens = [token for token in tokens if token not in en_stopwords]
  stemmed_tokens = [ps.stem(tokens)for tokens in new_tokens]
  clean_text = "".join(stemmed_tokens)
  return clean_text

In [14]:
X_test = ["good","okay","right","hey","do","no"]

In [15]:
x_clean = [getCleanedText(i)for i in X_train]
y_clean = [getCleanedText(i)for i in X_test]

In [16]:
x_clean

['hey',
 'hello',
 'hi',
 'goodmorn',
 'goodeven',
 'hey',
 'ye',
 'right',
 'ok',
 'okay',
 'sure',
 'fine',
 'its_ok',
 'okay',
 'caus',
 'cours',
 '',
 'dont',
 '',
 'pleas',
 'pleas',
 'never',
 'dont']

In [17]:
y_clean

['good', 'okay', 'right', 'hey', '', '']

#before classification we need to vectorise the parameter,then we need to further calculation


In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv = CountVectorizer(ngram_range=(1,2))

In [21]:
X_vec = cv.fit_transform(x_clean).toarray()

In [22]:
X_vec

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
print(cv.get_feature_names())

['caus', 'cours', 'dont', 'fine', 'goodeven', 'goodmorn', 'hello', 'hey', 'hi', 'its_ok', 'never', 'ok', 'okay', 'pleas', 'right', 'sure', 'ye']


In [33]:
xt_vect  = cv.transform(y_clean).toarray()
xt_vect

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#creating the multinomial naive bayes classifirer

*   List item
*   List item


```
# This is formatted as code
```



In [28]:
from sklearn.naive_bayes import MultinomialNB


In [29]:
mn = MultinomialNB()

In [31]:
mn.fit(X_vec,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [36]:
y_pred = mn.predict(xt_vect)
y_pred

array([1, 1, 1, 1, 1, 1])

In [43]:
if y_pred.any==1:
  print("the sentiment is nagative")
else:
  print("the sentiment is postive")

the sentiment is postive
